danielgtaylor/huma

- autoconfig.go
- openapi.go
- operation.go
- router.go
- schema/schema.go
Ref generation improvements to make future generated SDKs nicer and a few small fixes.
> Ref improvements

- middleware/recovery.go
> fix: dont redact headers that dont exist

- README.md
- responses/responses.go
- responses/responses_test.go
Accidentally misnamed the WriteContent responses helper function.  Fixing that.
> fix: responses.ServeContent -> responses.WriteContent

- resolver.go
> removed values.Has call due to backwards compatibility issues

- context.go
- openapi.go
- operation.go
This fixes up the DisableSchemaPropertynot actually include it in output or Schema Files
> Fix DisableSchemaProperty

- openapi.go
- router.go
- router_test.go
see: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object
Thanks for your work! 😄
> fix: add all `security scheme object` in OpenAPI 3.0.3

- patch.go
This PR fixes:
- Operations using the same resource model will now get unique `PATCH` operation IDs as long as their existing `GET` operations have unique IDs. This should easily handle any operation that can be split by `casing.Split`, e.g. `get-foo`, `get_foo`, `getFoo`, or `GetFoo` and turn it into `patch-foo`. If the operation doesn't start with a `get` or `fetch`, then we just prepend `patch-` to the existing operation ID.
Additionally:
- HTTP 415 responses are properly listed as returning `application/problem+json` like other errors
- `PATCH` operations now all have a default description set for documentation.
Existing tests continue to pass and provide coverage for the modified code.
> fix: ensure PATCH operation IDs are unique

- router.go
Go types can have a `.` in them but the `chi` router can't handle this if the non-parameter part of the route starts with (contains?) a `.`.  Given all the potential other special characters in a Go type name (in the context of generics), it was easier to just use a wildcard and check for the proper suffix.
In the future, it would be pretty easy to add support for a `.yaml` prefix.
The error handler here was pretty bare bones.  It didn't respond with RFC 7807 problems, etc.  So I made a more consistent error writer.
This is all to address issue #74.
> feat: schema handler can now handle schema names with special characters

- api.go
- cli.go
- defaults.go
- error.go
- error_test.go
- huma.go
- schema.go
- transforms.go
- validate.go
- wrk.lua
Various documentation & example updates to make usage in an IDE nicer and show how various features get used.
> docs: improve docs & examples

- README.md
- api.go
- chain.go
- huma.go
Add very simple impementation of middlewares
> huma: v2: add middlewares support

- README.md
Updating function signature to use `send sse.Sender` for `send.Data` example
> Minor update to SSE example in README.md

- docs/docs/why/index.md
Remove logos and replace with a developer quote.
> docs: remove logos [ci skip]

- adapters/adapters_test.go
- adapters/humabunrouter/humabunrouter.go
- adapters/humabunrouter/humabunrouter_test.go
- go.mod
- go.sum
Add support for *bunrouter.Router, and *bunrouter.CompatRouter (bunrouter.HandlerFunc, and http.HandlerFunc styles) routers. https://bunrouter.uptrace.dev
> Add bunrouter adapter

- huma.go
- huma_test.go
- validate.go
- validate_test.go
> Support array query parameters of primitives other than string

- huma.go
- huma_test.go
This fixes an edge case with composition, where a single anonymous field contains a `Resolve` method, which would get promoted by the Go compiler and be indistinguishable from a hand-written resolver method, resulting in the method being invoked twice (once on the parent, once on the actual struct with the resolver).
Now, when a type is found that matches one of the resolver interfaces, only named fields will continue to be traversed into to find other resolvers, skipping any anonymous fields whose method has been promoted or overwritten.
Fixes #234.
> fix: resolver should never be invoked twice

- docs/docs/features/bring-your-own-router.md
Adds Echo to BYOR page and moves FIber up to restore *alphabetical order*
> docs: adds echo router to BYOR page

- docs/docs/tutorial/your-first-api.md
Fix the directory for this broken link. Whoops...
> docs: fix broken link

- .github/FUNDING.yml
This adds a sponsor button for anyone who wants to sponsor the project financially.
Fixes #316.
> doc: Add sponsor/funding info

- api.go
This upgrades to the latest version of Stoplight Elements for the default documentation renderer.
> feat: upgrade to Stoplight Elements 8.1.0

- adapters/humafiber/humafiber.go
> fix: NewWithGroup accepting fiber.Router

- README.md
- README_CN.md
I want to contribute to the Chinese open source community
> feature: add Chinese document

- huma_test.go
@danielgtaylor 
Please let me know if anything needs to change.
resolve issue #388
> test: more tests for `cookie`

- transforms.go
Small quick fix for http schema when using 127.0.0.1
> Use plain http in $schema for 127.0.0.1

- docs/docs/features/cli.md
> fix: cli name example in docs

- README.md
- docs/docs/index.md
> docs: add new sponsor and quote

- README.md
- docs/docs/index.md
Adds our new monthly sponsor, thank you! 🎉
> docs: add new sponsor

- README.md
- docs/docs/index.md
> docs: add sponsors

- docs/docs/features/request-inputs.md
`MultipartFormFiles` were implemented but not documented, so I thought I could contribute and give back to your nice work.
> docs: describe MultipartFormFiles

- docs/docs/features/request-inputs.md
- huma.go
- huma_test.go
Hi! 
I need a way to handle null values in query parameters (and apparently I am not the only one #438 :slightly_smiling_face: ) so here is a PR that gives the possibility to wrap query parameter fields with custom types. 
It relies on implementing the `ParamWrapper` interface, which exposes as a `reflect.Value` the internal field that we want to use when parsing request parameters. 
`ParamReactor` (bad name, I know :see_no_evil: ) is another interface that can be implemented to specify a callback when a request parameter was parsed into our custom type.
```go
type ParamWrapper interface {
Receiver() reflect.Value
}
type ParamReactor interface {
OnParamSet(isSet bool, parsed any)
}
```
Example usage: 
```go 
type OptionalParam[T any] struct {
Value T
IsSet bool
}
// Define schema to use …
```
> feat: custom query parameter types

- README.md
- docs/docs/index.md
Minor update to list missed sponsor in docs.
> docs: update sponsors

- docs/docs/features/model-validation.md
- validate.go
> docs: fix model validator docs

- group.go
- group_test.go
- huma.go
This PR fixes an issue where switching from full paths to `huma.Group` while using convenience functions breaks the resulting OpenAPI backward compatibility. Since these two things (convenience functions and groups) operate at different layers, the operation's metadata is used to communicate when auto-generated operation ID and summaries have been used, enabling groups to regenerate those values if they have not been modified.
Fixes #754.
> feat: better group+convenience function interop

- docs/docs/features/auto-patch.md
The path for the autopatch package was incorrect.
> Incorrect import path for autopatch

- README.md
- README_JA.md
I added a README_JA.md to help Japanese developers to onboard on huma.
I'm a native Japanese who speak and understand English. I also have some experiences of translating and interpreting as well. I hope this helps huma to proliferate.
> add Japanese README (README_JA.md)

- autopatch/autopatch.go
- autopatch/autopatch_test.go
This should fix the broken build.
> fix: linter issues

- huma.go
Implemented suggestion from an [issue](https://github.com/danielgtaylor/huma/issues/781#issuecomment-2833290753).
> feature: improve default response status flow for head method

- README.md
- docs/docs/index.md
- docs/mkdocs.yml
I'm in need of a new job. Maybe someone using Huma wants me to join their company. This will be temporary and removed when no longer needed.
> docs: add links to hire me
