README.md, options.go, router.go, router_test.go
From an earlier conversation, this PR gives the server the ability to add what custom headers are allowed within CORS preflight requests.
=> Add configurable CORS middleware

README.md, resource.go, resource_test.go
I _think_ this is what is needed to add support for HTTP OPTIONS.
But I also think that I should add a more fledged out example of using Options.  Should I add one to [humatest_test.go](https://github.com/danielgtaylor/huma/blob/master/humatest/humatest_test.go)?
=> add support for HTTP OPTIONS

openapi.go, openapi_test.go, operation.go, resource.go, router.go
This change makes the OpenAPI generator code use a component schema registry and ref links rather than inlining every single model. This makes a huge difference in the resulting OpenAPI JSON size for even smaller APIs that document various possible error cases because the error model is so large and often repeated multiple times for each operation.
See also http://spec.openapis.org/oas/v3.0.3.html#components-object
Before:
```yaml
paths:
/foo:
get:
responses:
200:
content:
application/json:
schema: inline stuff repeated here...
```
After:
```yaml
components:
schemas:
name: inline stuff once here...
paths:
/foo:
get:
responses:
200:
content:
application/json:
schema:
$ref: "#/components/schemas/name"
```
This is supported by all tested OpenAPI tools (doc generators, SDK generators, mock …
=> feat: use refs for response models in generated OpenAPI

autoconfig.go, openapi.go, router.go, router_test.go
New settings for documenting gateway-based auth schemes and CLI autoconfiguration to make using e.g. [Restish](https://rest.sh) easier.
=> feat: security & autoconfiguration

resource.go, router_test.go
Tiny bug fix to make sure sub-resources get all fields copied. This gets used later when declaring operations on the sub-resources.
=> fix: copy router into sub-resources

README.md, context.go, go.mod, go.sum, graphql.go, graphql_model.go, graphql_paginator.go, graphql_test.go, openapi.go, resolver.go
This PR enables the use of an optional read-only GraphQL endpoint and introduces a `graphParam` struct field tag to facilitate field to parameter mappings for nested resources. See the README and test for more info & an example.
=> Add Read-Only GraphQL Support

middleware/recovery.go
Super simple header redaction for the recovery handler before it parses the request to a string and sends it to the application.
=> feat: enable applications to redact headers from recovery handler

context.go, go.mod, resolver_test.go, router_test.go
This fixes a bug where `time.Time{}` was improperly handled by `mapstructure`, which is now replaced with a custom shallow copy function that behaves better. Also handles struct pointers properly now for adding `$schema` fields.
=> fix: serialization of time.Time and struct pointers

context.go, graphql_model.go, schema/schema.go
Small fix for how zero values were getting turned into a map.
Also updates the code to support generating schemas and GraphQL from the new Go 1.18 generics (type parameters) feature, which introduces some new fields into the generated types at compile time that we need to ignore.
=> fix: better handling of zero values; no panic for generic types

context.go, humatest/humatest.go, humatest/humatest_test.go, middleware/recovery.go, middleware/recovery_test.go
This PR waits to redact sensitive headers until just before they get dumped by the panic recovery middleware logger. Also fixes a minor typo I found the other day.
=> fix: redact headers after handler runs; fix typo

resolver.go
This fixes errors where the location looks like `body.` but should really be `body`.
=> fix: trim trailing dot from error locations

README.md, context.go, operation.go, resolver.go, resolver_test.go, router_test.go
This PR changes the status code behavior for errors to attempt to return more specific status codes when possible while still striving for exhaustive error responses. As can be seen in the README, the new flow is:
```mermaid
flowchart TD
Request[Request has errors?] -->|yes| Panic
Request -->|no| Continue[Continue to handler]
Panic[Panic?] -->|yes| 500
Panic -->|no| RequestBody[Request body too large?]
RequestBody -->|yes| 413
RequestBody -->|no| RequestTimeout[Request took too long to read?]
RequestTimeout -->|yes| 408
RequestTimeout -->|no| ParseFailure[Cannot parse input?]
ParseFailure -->|yes| 400
ParseFailure -->|no| ValidationFailure[Validation failed?]
ValidationFailure -->|yes| 422
ValidationFailure -->|no| 400
```
The change is fairly small & unobtrusive. Several tests have been …
=> feat: return more specific error codes

context.go, operation.go, router_test.go
This makes it so you can set a response status code of `0` to signify this is the OpenAPI "default" response, and updates a couple places to allow the responses to get written without causing errors. This helps in the rare case that you have a bunch of response status codes you could return and would rather use a default than list them all out.
=> fix: accept status code 0 as default response

resolver.go, resolver_test.go
Today in order to use a boolean with queryparams it needs to be set like this: `?param=true`, now you can set it with `?param` or `?param`
=> Huma now accepts naked boolean queryparams

middleware/encoding.go, middleware/encoding_test.go
This change updates the content encoding middleware to be aware of the `Content-Encoding` response header. If already present, it will act as a no-op rather than double-encoding the response body. Use cases:
- Enable custom content encodings within operation handlers
- Prevent double-encoding if multiple content-encoding middlewares exist
=> fix: prevent double content-encoding

README.md
Hello! Sorry if this isn't timely or an appreciated suggestion, but I'm going to make it anyway 🙂
Personally, I think Huma is nearly ready to adopt widely, and I would love to see the project enjoy widespread success!
To that end, I know it might seem silly, but this adds some "first time user" friendliness to the README, I think.
=> docs: add TOC to README.md plus Install section

graphql.go, graphql_test.go
This PR adds a feature to ignore certain URL path prefixes when generating the GraphQL interface. This allows you to opt-out for some paths or groups of paths in the HTTP API, for example if they make no sense in the GraphQL interface or if multiple URL paths (temporarily) resolve to the same Huma handlers in your API.
=> feat(graphql): add ignore prefixes config option

context.go
Saving having to add Headers method to all the responses. I have both a Auth Framework as well as Tracing middleware thats adding headers to every request.
=> add AddAllowedHeaders function to whitelist common headers

openapi.go, openapi_test.go, operation.go, router_test.go, schema/schema.go, schema/schema_test.go
This fixes the tests, fixes a bug where a request with `$schema` can fail validation, and writes a new round-trip test.
=> fix: $schema in request, fixes #48

README.md, context.go, go.mod, go.sum, operation.go, patch.go, patch_test.go, resolver.go, router.go, router_test.go
Adds optional automatic `PATCH` operation generation when a `GET` and a `PUT` are available for a resource. Supports conditional requests and both JSON Merge Patch & JSON Patch standards out of the box.
Underneath the hood it literally just calls the `GET`, applies the patch to the returned data, and then submits the `PUT` with that updated data. There are no optimizations made, but this makes it easy for clients to make small updates to large resources in a standardized way.
=> feat: automatic PATCH operation generation

patch.go, patch_test.go, resolver.go
This adds an additional `nil` check to prevent a panic when registering or handling a request for a `PUT` operation without a request body. Also adds a test to exercise the functionality and confirm the auto-patch feature skips such operations.
=> fix: panic on put without body

operation.go, operation_test.go
This adds support for the [OpenAPI flag/marker deprecated](https://swagger.io/specification/#fixed-fields-8) for operations.
=> feat: add deprecated flag to operations

patch.go, patch_test.go
This will mark auto-generated `PATCH` operations to also be flagged as `deprecated` if the corresponding `PUT` operation is flagged as so.
=> fix: auto-mark patch deprecated

examples/bookstore/bookstore.go, operation.go, patch.go, resolver.go, router.go, router_test.go
Addresses two issues with stable/consistent OpenAPI generation:
- Properties are generated in random order. https://github.com/danielgtaylor/huma/issues/68
- Operation parameters may be added in random order. 
- This is particularly problematic in tools like [OpenAPIGenerator](https://github.com/OpenAPITools/openapi-generator) because parameter ordering matters for SDK generation.
Properties will now output in lexicographical order for consistency. Operation parameters will honor the order they're defined in the struct. 
A new example called `bookstore` is also added to demo a slightly more complex OpenAPI configuration where the schema ordering matters.
=> fix: stable OpenAPI property and param ordering

middleware/encoding.go
Huma currently overrides the `Vary` response header to always be `Vary: Accept-Encoding`. This is problematic because it overrides other potential headers the server might set to indicate how the browser should cache the resource. For example, `Vary: Origin` may be needed to avoid CORs when the same resource is being called by multiple origins [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching).
This PR instead has Huma add the `Vary: Accept-Encoding` to avoid overwriting other `Vary` values already set.
=> fix: don't override vary header

openapi.go, operation.go, resolver.go, schema/schema.go
I'm submitting this pull request in response to issue #75.  
This keeps track (during recursion) of what (`struct`) types have already been defined.  If it encounters an already defined schema, it simply replaces it with an `$ref` rather than elaborating the schema again (and again, and again).
This isn't perfect.  It makes some assumptions about the schema name.
Note, even though the `$ref` I added was something like `./schemas/Foo`, when it gets generated by the schemas endpoint it is `./schemas/Foo.json` which is not good.  Specifically, I'm thinking about cases where we might want to put in a `$ref` that is something like `#/definitions/Foo`.  In that case, no `.json` is required (or desirable).  So you might want to consider revisiting the logic that appends to the `$ref`s.
The other …
=> feat: avoids infinite recursion

router.go, router_test.go
This allows us to query the router for information.  I've added a GetOperation method so we can query for information about a given operation.  This is useful in hypermedia APIs because it allows us to link across different endpoints without having to hardwire paths.  Instead, the cross-referencing is done via operation id.
=> feat: ability to fetch router from huma context

context.go, middleware/logger.go
This seems to address issue #88.  As the standard library docs suggested, the problem is related to wrapping `ResponseWriter` instances.  I went through and implemented a `Flush` method for the `statusRecorder` and `huma.Context` types.  I tested this with a resource handler that was generated server side events (_i.e.,_ called `ctx.Write(...)` multiple times invoking `.Flush()` after each).  Running `curl -N ...` showed that the output was, in fact, getting flushed (which was definitely **not** the case before these changes).
I haven't tested this with an SSE client, but just running `curl -N` seems like an adequate test of the functionality for now.
=> fix: implement Flusher interface for wrapped ResponseWriters

context.go
According to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_response_headers), there are two standard CORS headers that are missing here, `Access-Control-Expose-Headers` and `Access-Control-Allow-Credentials`.
=> fix: add missing CORS headers

README.md, openapi.go, operation.go, resolver.go, router.go, schema/schema.go
This continues the work from #86, and reverts the new behavior to be behind a feature flag that must be enabled to not break existing service's generated SDKs. To enable the new behavior, just set `schema.GenerateInline = false`.
=> fix: properly instantiate nested schemas, replaces #86

go.mod, go.sum
The [second line-item](https://github.com/graphql-go/graphql/releases/tag/v0.8.1) for the release says they have addressed the CVE issue.
This is to address [CVE-2022-37315](https://github.com/danielgtaylor/huma/security/dependabot/30)
=> chore(deps): upgrade graphql-go to address CVE

router.go
This change enables people to start playing with the v2 branch (requires a `replace` directive in your `go.mod` at the moment pointing to the v2 branch).
```go
import (
"github.com/danielgtaylor/huma"
humav2 "github.com/danielgtaylor/huma/v2"
"github.com/danielgtaylor/huma/v2/adapters/humachi"
)
// ...
mux := chi.NewRouter()
app := huma.NewWithMux("My API", "1.0.0", mux)
// ... register v1 routes
// Set up v2 to use the same mux & register v2 routes
api := humachi.New(mux, humav2.DefaultConfig("My API", "1.0.0"))
humav2.Register(/* ... */)
app.Run()
```
Note: this does not merge the generated OpenAPI. You can manually use a Huma v1 Open API hook to do that to merge the v2 `api.OpenAPI()` if desired.
=> feat: method to use custom chi mux; enables incremental adoption of v2

README.md
This PR fixes a couple of links in the README so they show the correct coverage and point to the right version of the Go docs.
=> docs: fix docs links

registry.go, schema_test.go
Simpler refs & links when using named types with generics since `[` and `]` don't work well.
=> fix: better support of generic named types

schema.go, schema_test.go
This PR ports v1 logic for getting all fields from all embedded objects in a breadth first search, taking care to keep track of the field's parent as these are used in v2 for naming hints.
The schema generator had good coverage but didn't have a specific test for this scenario, so thanks for pointing it out! There is a test now to ensure this works as expected, including field overrides.
Fixes #113.
=> fix: incorrect schema for embedded structs

codecov.yml, huma.go, huma_test.go, schema.go
This PR adds some additional tests and corrects an issue with parameter date/time parsing and validation. The custom `timeFormat` of `2006-01-02` and `15:04:05` are also correctly identified as JSON schema `date` and `time` now as well, so additional validation is possible.
=> fix: param date/time parsing, better tests/coverage

adapters/humachi/humachi.go, adapters/humafiber/humafiber.go, adapters/humagin/humagin.go, adapters/humahttprouter/humahttprouter.go, adapters/humamux/humamux.go, api.go, huma_test.go, humatest/humatest.go
There is currently no way to get multipart form from a huma context. I need this feature in the Resolve method because I get a multipart request in one of the endpoints. At the moment the only way to get the form is through reflection, which I would like to avoid, as I think other developers would like to avoid as well.
I also renamed adapters struct methods receivers to 'c'. At the moment the adapters had 'c' and 'ctx' mixed in.
=> Add GetMultipartForm method to huma context

api.go, api_test.go, conditional/params.go, error.go, error_test.go, huma.go, huma_test.go, schema.go, validate.go, validate_test.go
Improved tests & coverage for v2. Fixed a few issues:
- Incorrect `time.Time` handling in some cases, or unexpected validation failures
- Better validation of pre-parsed params (e.g. `int` vs the JSON/CBOR `float64`, `[]string` fixes)
- Default content type assumption for request bodies if missing `Content-Type` header
- `Status304NotModied` → `Status304NotModified` 🤭
=> fix: improved tests, fixed a few small issues

README.md, validate.go, validate_test.go
Adds a basic convenience utility for validating data against model schemas outside of the normal request/response flow.
Fixes #121.
=> feat: add convenience model validator

huma.go, huma_test.go, schema.go, validate.go, validate_test.go
Adds support to the schema and validation for `oneOf`, `anyOf`, `allOf`, and `not` schemas. An example is included how these combined with a raw body can be used to create an operation with multiple input types.
Lays the groundwork to fix #128, though I want to revisit validation error messages and see how struct field tags could make use of these new features (particularly one-of support).
=> feat: oneOf, anyOf, allOf, not schema support

huma.go
This fixes #130 by making sure the generated docs send the request the correct way. It does not support exploded params as input, which would be a larger task (but one I'm willing to review/merge if anyone wants to take it on).
=> fix: set explode=false for query params

adapters/humafiber/humafiber.go
This makes the use of `StreamRequestBody` optional when using Fiber. The adapter will return a reader for the body but may have already cached the input bytes.
=> fix: allow fiber without StreamRequestBody, fixes #127

transforms.go
Hey @danielgtaylor 👋🏼 
Firstly - just found Huma and loving it - very quickly I've been able to get a TRPC-like workflow running which is amazing.
It looks like Chi does not provide the Host header through the Header func but it is explicitly available via the Host func. This meant the `$schema` never had a hostname and would return `https:///schema...`.
=> Fix: Update transforms.go to use explicit Host function from huma.Context

README.md
Small improvement to document the behavior of CLI option naming and how to override it.
=> docs: improve CLI docs around option naming

examples/param-reuse/main.go
This adds an example of re-using a parameter in both the URL path and the response body.
=> fix: add param re-use example, fixes #94

README.md, examples/omit/main.go, huma.go, registry.go, schema.go, schema_test.go
This PR adds an optional `huma.SchemaProvider` interface, which a type can implement to provide its own custom JSON Schema, disabling the built-in schema generator and enabling customized behavior for request/response body fields.
When combined with custom serialization logic, this can enable use-cases like determining whether a field was sent at all, is `null`, or is a value. A new example is added to showcase this functionality.
As part of this work, a small change in `huma.go` is made to properly set the `operation.requestBody.required` OpenAPI field, and this field is then later checked to determine whether the body is required. This works much better with custom operation schemas, which would not be required before even when that field was set.
Fixes #137.
=> feat: support custom field schemas; add omittable example

examples/oneof-response/main.go, huma.go
This PR adds an example showing how you can return different responses depending on some input param while providing a `oneOf` schema in the OpenAPI for the operation.
It includes a small fix to make sure not to overwrite custom schemas, if set.
Fixes #35. In the future such functionality could be wrapped in a nicer way, but for now this lays the groundwork to make the feature possible. PRs to add high-level utilities around it are welcome.
=> feat: add example for oneOf response, fix custom schema usage

schema.go, schema_test.go
Small fix to better support inputs/outputs with fields that are pointers and provide an example for the generated schema.
Fixes #18.
=> fix: prevent panic on examples for pointer field types

README.md, huma.go, huma_test.go
> :whale: In general, you should consider path parameters or a body for required arguments.
While discouraged, this enables marking query & header params as required via struct field tags, like this:
```go
type MyInput struct {
Start time.Time `query:"start" required:"true"`
}
```
Fixes #21.
=> feat: allow making query/header params required

README.md, huma.go, huma_test.go, schema.go
This PR makes it easy to support basic file uploads using the `RawBody []byte` request field. It also enables more docs/examples/etc on the request body, and the ability to set a custom content type.
Fixes #28.
=> feat: better support for file uploads

huma_test.go, transforms.go
This PR modifies the schema link transformer to add the `$schema` field to request bodies as well as response bodies, so that round-trips of the data work.
Fixes #59
=> fix: add $schema field to input to allow round-trips

README.md, huma.go, huma_test.go
Enable resolvers to return an error which satisfies `huma.StatusError` in order to set a custom response status code. This means the utility HTTP errors can be used, like `huma.Error403Forbidden`, if desired, but also anything that implements that interface will work.
Here's a minimal example:
```go
type MyInput struct{}
func (i *MyInput) Resolve(ctx huma.Context) []error {
return []error{huma.Error403Forbidden("nope")}
}
```
Note: errors are processed in-order and the last one wins. It's best to use this feature *very* sparingly.
Fixes #107.
=> feat: allow resolvers to set a custom response status code

schema/schema.go, schema/schema_test.go
This backports a fix from Huma v2 into Huma v1, enabling the use of examples for fields which are pointers. An example is added to the existing tests.
=> fix: backport Huma v2 example pointer fix from #148

api.go, api_test.go, cli_test.go, error.go, error_test.go, huma.go, huma_test.go, schema_test.go, validate_test.go
This PR does the following things:
1. Split the transform functionality out of `API.Marshal(...)` so that marshaling no longer needs access to the full request context.
2. Better handle failures with transforming or marshaling responses after a response status code has already been sent on the wire.
3. Rename test package from `huma` → `huma_test` and dogfood using `humatest` now that there is no more circular dependency requiring yet another adapter implementation.
=> feat: split transform/marshal, reorg tests & dogfood humatest

autopatch/autopatch.go, autopatch/autopatch_test.go, humatest/humatest.go
This PR ports over the Huma v1 autopatch tests to Huma v2, adds a bit to them, and makes a few small fixes to the v2 autopatch implementation:
1. Only generate patch operations when the get/put type is an object.
2. Fix an empty error that was sent to `WriteErr`
3. Fixed PUT request URL to use the original URL so that path params are set properly
4. `humatest` better supports `...+json` media types, like `application/problem+json` error responses
=> fix: autopatch fixes, add tests

README.md, api.go, autopatch/autopatch.go, autopatch/autopatch_test.go, autoregister_test.go, conditional/params.go, error_test.go, examples/param-reuse/main.go, huma.go, negotiation/negotiation.go, openapi.go, queryparam/queryparam.go, resolver_test.go, sse/sse_example_test.go, sse/sse_test.go
This PR includes a ton of documentation updates, including adding the rest of the OpenAPI 3.1 spec descriptions to the corresponding Go structs/fields and including some examples from the spec. Some tests are updated as well and a few new examples are included that render in the Go docs.
=> docs: lots of docs updates, a few more tests/examples

README.md, autopatch/autopatch.go, autopatch/autopatch_test.go, openapi.go
This PR:
- Updates some docs
- Makes `autopatch.PatchResource` public for more control (if desired)
- Adds `huma.Operation.Metadata` to store arbitrary config data
- Enables autopatch opt out via op metadata `{"autopatch": false}`
- Updates some tests to use the new humatest test API features
=> feat: operation metadata and autopatch disable

examples/sse/main.go
This PR adds a new example showcasing how to use the `sse` package to send Server Sent Events responses to clients from a single producer goroutine, mimicking a real fan-out use-case.
=> feat: add Server Sent Events example

chain.go, huma.go, huma_test.go
This fixes the path buffer value for path/query/header params when used with/as resolvers. It also panics on invalid combinations like pointer+param or pointer+default, to help prevent common but very difficult to track down subtle bugs like values not getting set as expected. Some of that could be made possible later, but shouldn't block v2.0.0 from being released.
=> fix: better paths for resolvers, prevent subtle mistakes

README.md, huma.go, huma_test.go
This PR prevents sending empty string/time headers over the wire, improves documentation, and adds a benchmark comparing global vs. inline/lambda handler functions (which turn out to be about equal in performance).
=> fix: omit empty string/time headers from response

huma.go
Some transforms may set or update headers, and if the status has already been sent then header updates will fail silently. This ensures the status is sent *after* the transforms, which has the added benefit of producing non-success status codes if transforms panic or fail.
=> fix: set response status after transforms

autopatch/autopatch.go
This uses a function that compares the encoded JSONs and ignores whitespace differences.
=> fix: better comparison of encoded payloads for patch, fixes #73

.github/workflows/docs.yaml
Run in the correct directory when building/deploying.
=> fix: mkdocs deploy path

.github/workflows/docs.yaml
Ensure this runs when the workflow file itself changes. Also add a manual trigger in case we need to rebuild from the latest.
=> fix: trigger docs workflow on edits

docs/docs/features/bring-your-own-router.md, docs/docs/features/json-schema-registry.md, docs/docs/features/model-validation.md, docs/docs/features/openapi-generation.md, docs/docs/features/operations.md, docs/docs/features/request-inputs.md, docs/docs/features/request-validation.md, docs/docs/features/response-outputs.md, docs/docs/features/response-serialization.md, docs/docs/features/schema-customization.md, docs/docs/features/test-utilities.md, docs/docs/tutorial/cli-client.md, docs/docs/tutorial/client-sdks.md, docs/docs/tutorial/installation.md, docs/docs/tutorial/sending-data.md, docs/docs/tutorial/writing-tests.md, docs/docs/tutorial/your-first-api.md, docs/docs/why/index.md
While testing with gh-pages we need to support relative links as the site isn't hosted at the root of the domain. This also fixes a broken link to the auto-patch docs.
=> docs: fix a few links

docs/docs/CNAME
This makes sure the domain name doesn't get overwritten on new builds.
=> docs: make CNAME permanent [ci skip]

.github/workflows/ci.yaml, .golangci.yml, autopatch/autopatch.go, cli_test.go, conditional/params_test.go, docs/asciinema-run/main.go, error_test.go, huma.go, huma_test.go, openapi.go, schema.go, schema_test.go, sse/sse_test.go
This adds support for [golangci-lint](https://golangci-lint.run/) if installed, and runs the linter on pull requests.
If using VSCode, you can use the following config line to enable linting whenever you save:
```json
"go.lintTool": "golangci-lint",
```
=> chore: add linter & rules config

huma_test.go
This adds a new test to cover more cases of `default` tag usage, including primitives, slices, and slices of structs.
=> test: add body and nested defaults test

api.go, huma.go, huma_test.go
Return a 415 when the body unmarshaling fails due to the client-reported content type.
=> fix: use 415 status for bad input content type

validate.go, validate_test.go
Enables validation for `map[any]any` as well as providing a bunch of tests for those inputs. Notably this is used by CBOR and can be used by other formats as well that support more than just `string` keys for maps. There's a small bit of code duplication in an effort to keep memory allocations down, so that is intentional.
=> fix: enable validation for map[any]any used by some formats

adapters/adapters_test.go, adapters/humamux/humagmux_test.go, adapters/humamux/humamux.go
This also fixes the package name to match the import path. Crucially this should not break existing imports!
Fixes #179. Tested via some manual testing, but should consider adding more basic tests to the adapter packages (or maybe a new package to test each adapter with common scenarios?).
=> fix(gorilla/mux): properly register operations with the router

adapters/humabunrouter/humabunrouter_test.go, docs/docs/features/bring-your-own-router.md
Adds docs about BunRouter support to https://huma.rocks/features/bring-your-own-router/ and removes a benchmark that was just testing Chi again since the older Huma v1 can't use any other router.
=> fix: document bunrouter support; remove incorrect benchmark

docs/docs/features/cli.md, docs/mkdocs.yml
Various minor improvements to the docs.
=> docs: improved docs; auto light/dark mode

.github/workflows/ci.yaml
This should ensure the PR checks run on pull requests from other users rather than just pushes from maintainers.
=> chore: trigger CI on pulls and push-on-main

huma.go, huma_test.go
This PR addresses the two CodeQL scan alerts:
- https://github.com/danielgtaylor/huma/security/code-scanning/1
- https://github.com/danielgtaylor/huma/security/code-scanning/2
This is addressed by reading into a value of size `strconv.IntSize` rather than 64, as some systems will limit `int`/`uint` to 32 bits.
It also increases code coverage a bit with examples of array query params that fail to parse.
=> fix: integer conversion CVE, improved coverage a bit

registry.go, schema_test.go
Updates the default schema naming function to support generics using types defined in other packages, such as the included test example using `SchemaGeneric[time.Time]`. The JSON names and paths generated in the schema are now valid and documentation renders correctly.
Fixes #189
=> fix: schema naming for generics + package types

schema.go, validate_test.go
Manually created schemas were not having `propertyNames` and `requiredMap` set up, which meant that validation of the inputs for those manual schemas was incomplete. This fixes it by backfilling any pre-computed data during the `PrecomputeMessages()` call, ensuring the validation works as expected.
This is related to some more complex scenarios described in #185 where schemas can't be generated from structs.
=> fix: better validation of manual schemas

.gitignore, go.mod, registry.go, registry_test.go, schema_test.go
This builds on #199 to generate SDK-friendly names for a bunch of generics scenarios, including unicode support for individual components. Lots of new test cases added which should cover the gamut of possibilities.
=> fix: enhanced generic schema naming

.gitignore, registry.go, registry_test.go
PR #195 fixed ISSUE #189. But regex matched a shorter string when a generic parameter is an slice( that means there's embedded brackets). 
And the expression is more complex when the generic parameter is another generic type. 
Propose to use a full path name as  the name is used as an ID and reference in the yaml. Readability is trivial.
=> fix ref name contains recursive brackets '[]'

adapters/humago/humago.go, adapters/humago/humago_test.go, docs/docs/features/bring-your-own-router.md, docs/docs/why/index.md
This enables the use of the new Go 1.22 routing additions to the `http.ServeMux` (methods and path params) via a new `humago` adapter. Note that this requires using `gotip` or the Go 1.22 release candidate and you **must** have `go 1.22` in your `go.mod` file to enable the new behavior.
=> feat: experimental Go 1.22 ServeMux support

docs/docs/how-to/oauth2-jwt.md, docs/mkdocs.yml
This takes some of the information from #202 and #186 and tries to put together a simple how-to for people wanting to add OAuth 2.0 based auth with JWTs to their API.
=> docs: Add OAuth 2.0 & JWT how-to

api.go
Sending the Referrer header is unnecessary and may leak some private data (unlikely to be highly-sensitive, but I think the point is still valid).
=> fix: avoid sending referrer header to unpkg

api.go
Using an unversioned import can become a security issue in case of compromised npm repositories or compromised unpkg.
To make the situation a bit safer-by-default, I propose a switch to versioned imports + the use of [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to ensure users have a comparable level of security for the JS side as they do for the go side.
IMHO the trade-off between "bleeding-edge" and "security" seems to fall in favor of security, especially since uses who want the bleeding-edge can still override the docs handler.
WDYT?
=> proposal: switch to versioned spotlight and add integrity check

sse/sse.go
This fixes a small issue where the generated SSE `oneOf` schema array contained empty `null` entries, one for each real entry in the array. The fix is to set the initial length of the Go slice to zero.
Fixes #207.
=> fix: SSE oneOf schema contained null entries

api.go
This fixes #215 by allowing the integrity check to proceed via CORS request.
See also https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
=> fix: add crossorigin config for sha integrity check

registry.go
print the exact conflict items:
```go
panic: duplicate name: ResponseGenericOrderData, new type: main.Response[my-app/module/submodule2.Generic[my-app/module/submodule2.OrderData]], existing type: main.Response[my-app/module/submodule.Generic[my-app/module/submodule.OrderData]]
```
the original log message is hard to read especially when there's tens of API entries:
```go
panic: duplicate name ResponseGenericOrderData does not match existing type. New type main.Response[my-app/module/submodule2.Generic[my-app/module/submodule2.OrderData]], have existing types map[submodule.Generic[my-app/module/submodule.BizData]:true submodule.Generic[my-app/module/submodule.OrderData]:true submodule.BizData:true submodule.OrderData:true huma.ErrorDetail:true …
```
=> log accurate error message when there's duplicate registry name

adapters/humabunrouter/humabunrouter.go, adapters/humachi/humachi.go, adapters/humaecho/humaecho.go, adapters/humagin/humagin.go, adapters/humago/humago.go, adapters/humahttprouter/humahttprouter.go, adapters/humamux/humamux.go
This makes multipart form parsing max memory usage configurable for most routers (Fiber does not have a memory limit for this feature). For example:
```go
import "github.com/danielgtaylor/huma/v2/adapters/humachi"
// Allow up to 5 MiB per form submission.
humachi.MultipartMaxMemory = 5 * 1024 * 1024
```
Fixes #205.
=> feat: make multipart form max memory configurable

docs/docs/how-to/oauth2-jwt.md
Fix minor errors in OAuth2 how to, but huma.WriteErr requires huma.API as first argument and there no way to obtain it in middleware. I was thinking about replacing it with http.Error, but it requires http.ResponseWriter and huma.Context doesn't implement it. So i'm stuck there.
=> Errors in OAuth2 how to examples

README.md, docs/docs/features/index.md, docs/docs/features/response-errors.md, error.go
This PR provides some README updates to link to some articles and quote some user feedback, as well as the update from RFC 7807 → RFC 9457 structured errors, which is a backward-compatible change (so just listing that we support the latest spec).
=> docs: README updates & RFC 9457 errors

huma.go, huma_test.go
Prevent generating a default `application/json` response when there is already a response defined, for example when returning binary outputs like images.
Fixes #246
=> fix: do not generate json response for binary outputs

docs/docs/features/middleware.md
This adds a small section to the docs for returning nice standardized well structured errors that utilize the API's content negotiation and marshaling from a router-agnostic middleware. Thanks to #241 for pointing out this was missing!
=> docs: add doc about middleware errors

docs/docs/features/request-inputs.md
Improves the docs around inputs like `text/plain` and others that aren't structured data like JSON that needs to be parsed and validated. Adds an example as well to show how to use these features properly.
Fixes #249.
=> docs: improve docs for unstructured request bodies

api.go
Elements "Try It" feature defaults to omitting credentials cookies, which causes APIs authenticated with cookies not to work.
This PR changes [elements credentials policy](https://docs.stoplight.io/docs/elements/b074dc47b2826-elements-configuration-options) to `same-origin`, [just like the default for a fetch request](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials#same-origin) :
> Send user credentials (cookies, basic http auth, etc..) if the URL is on the same origin as the calling script. This is the default value.
=> change elements try it credentials policy to same-origin

docs/docs/features/request-validation.md, schema.go, schema_test.go
This enables better control over the generated JSON Schema `additionalProperties` field value for objects. By default it remains `false` (aka strict validation), but this enables you to use an anonymous field to set it to `true` (aka loose validation) if desired:
```go
type PartialInput struct {
_      struct{} `json:"-" additionalProperties:"true"`
Field1 string   `json:"field1"`
Field2 bool     `json:"field2"`
}
```
Fixes #252.
=> feat: better control over object additionalProperties

codecov.yml, cookie.go, docs/docs/features/middleware.md, docs/docs/features/request-inputs.md, docs/docs/features/response-outputs.md, examples/cookies/main.go, huma.go, huma_test.go
This PR does the following:
1. Adds a `cookie` field tag for cookie parameters. Fields can be any of the normal parameter types, plus `http.Cookie` is supported to get the entire parsed cookie.
2. A new function `huma.ReadCookies(ctx huma.Context, filter string)` is provided for reading/parsing cookies from one or more `Cookie` headers in a router-agnostic way and without needing to modify the `huma.Context` interface. This function can be used in middleware to read cookie values.
3. If a response header type supports `fmt.Stringer` (aka a `String() string` method), then that is used to serialize the header.
4. If a response header type is a slice, then `huma.Context().AppendHeader(...)` is used to write multiple headers with the same name.
5. As a result of 3 and 4 above, `http.Cookie` …
=> feat: better support for cookies

cli.go, cli_test.go, docs/docs/features/cli.md
This PR fixes the default CLI name to use the name of the executable being called, and adds documentation about how to manually set both the app name and version, if desired.
Fixes #264.
=> fix: set CLI name from executable, add docs for name/version

api.go
Thank you for the fantastic work your team has done. When I use huma for a demo, I noticed that the documentation does not display correctly on my extended screen, as follows:
I found a solution on the Stoplight documentation website that suggests resolving the issue by adding a style configuration to the body.
```html
<body style="height: 100vh;">
<stoplight-api />
</body>
```
[Stoplight Layout](https://docs.stoplight.io/docs/elements/d536b917a4e1d-layout)
Hope this issue can be fixed!
=> fix: Set body height to 100% of the viewport height

transforms.go
So far using a type as `Body` on a response type containing unexported fields results in a panic:
```
panic: reflect.StructOf: field "config" is anonymous but has PkgPath set
goroutine 1 [running]:
reflect.runtimeStructField({{0x105753038, 0x6}, {0x105778f34, 0x27}, {0x1059311a8, 0x1058b15e0}, {0x10575303f, 0x8}, 0x0, {0x14000352668, ...}, ...})
/opt/homebrew/Cellar/go/1.22.0/libexec/src/reflect/type.go:2538 +0x1c8
reflect.StructOf({0x14000270008, 0x10, 0x14000548508?})
/opt/homebrew/Cellar/go/1.22.0/libexec/src/reflect/type.go:2189 +0x274
github.com/danielgtaylor/huma/v2.(*SchemaLinkTransformer).OnAddOperation(0x140005a2150, 0x140005aa0b0, 0x14000548601?)
.../huma/transforms.go:110 +0x2d0
```
As I am using `ent` (entgo.io) that is subpar, because the structs generated by `ent` contain …
=> fix: allow response types to contain unexported fields

huma.go, huma_test.go
This PR ensures the underlying errors from transforms and/or writes are wrapped and work with `errors.Is(...)` rather than being converted to strings.
Fixes #272.
=> fix: return wrapped errors on transform or write failure

docs/docs/why/index.md
This is no longer experimental.
=> docs: remove experimental flag for Go 1.22+

docs/docs/features/operations.md, huma.go
This extends the convenience functions further by generating phrases and sentences for `Summary` and `Description` respectively.
I didn't want to add further dependencies like `cases` and whatnot since I'm not sure if you're fine with that or not. This looks a bit hacky but it does the trick for a basic implementation.
Tell me what you think :)
=> feat: add convenience functions for summary and description

README.md, cli.go, docs/docs/features/cli.md, docs/docs/how-to/custom-validation.md, docs/docs/how-to/graceful-shutdown.md, docs/docs/how-to/image-response.md, docs/docs/how-to/migrate.md, docs/docs/tutorial/sending-data.md, docs/docs/tutorial/service-configuration.md, docs/docs/tutorial/writing-tests.md, docs/docs/why/what-about-design-first.md, examples/cookies/main.go, examples/greet/main.go, examples/omit/main.go, examples/oneof-response/main.go, examples/param-reuse/main.go, examples/resolver/main.go, examples/spec-cmd/main.go, examples/sse/main.go, examples/v1-middleware/main.go, humacli/humacli.go, humacli/humacli_test.go
This PR moves the built-in optional CLI functionality into its own `humacli` package and updates all examples & docs. The existing CLI functionality stays but is marked as deprecated to give people time to move to the new package. Switching is fairly easy:
- `huma.NewCLI` → `humacli.New`
- `huma.CLI` → `humacli.CLI`
- `huma.Hooks` → `humacli.Hooks`
- `huma.WithOptions` → `humacli.WithOptions`
The plan is to **remove the old functionality a few releases from now**. This will be a small breaking change to facilitate the removal of some dependencies that are not used by everyone, but will be treated as a bug fix.
Related to #290. This doesn't fix it yet, but sets us on the track to doing so soon.
=> fix: move CLI to its own package, deprecate huma.NewCLI

validate.go, validate_test.go
Hi! Current string length validation made with go's standard `len` function works incorrectly with non ascii characters. So if there any non-english symbols `"maxLength"` validator will fail when it shouldn't.
In this PR I'v replaced `len` with `utf8.RuneCountInString`. Instead of number of bytes it will calculate number of runes. 
It will resolve most issues. But it don't take into account [unicode text segmentation](https://unicode.org/reports/tr29/). So if there will be symbols such as emojis, that consists of more than one unicode character it still will calculate length incorrectly. More info could be found [here](https://stackoverflow.com/a/12668840). 
So may be the next step is to add usage of https://github.com/rivo/uniseg. But considering it is a big change and new dependancy may …
=> fix: length validation for utf8 strings

schema.go, schema_test.go
This pull request fixes issue #299 by checking if a field was already processed by its original name and not by the name given through a tag.
=> fix: issue 299

schema.go
This also fixes a test that fails intermittently by ensuring the output is always the same.
=> fix: make dependent error deterministic

validate.go, validate_test.go
This was missed in #303, needed to potentially support other formats like CBOR/msgpack/YAML/etc that may create maps where keys may not all be strings. The one caveat is the checked dependent key type will always be a string, but I think that's acceptable for now.
=> feat: support dep required for map[any]any

openapi.go
Small fix based on the spec here: https://spec.openapis.org/oas/v3.1.0#oauth-flow-object. This should not be included for other flows, so we have to mark it as `omitempty`.
Fixes #315.
=> fix: authorizationUrl is only required for implicit/authcode

huma.go, huma_test.go
Fixes a small miss where `op.SkipValidateParams` is set and we skipped most validation but not the required check.
Fixes #317.
=> fix: skip param required check if SkipValidateParams is set

schema.go, validate_test.go
Adds a new `patternDescription` struct tag to allow for human-readable error messages when using the pattern tag. 
Error messages are formatted like `expected string to be {description}` - this allows the user to use their own articles while still being consistent with the other validators
=>  feat(validation): flexible validation messages for pattern tag

huma.go, huma_test.go, schema.go, schema_test.go
My machine has crashed when I've tried to use Huma for the new micro-service that I'm developing.
```
// Node is a custom type for testing recursive definition for huma.Register
type Node struct {
Name  string          `json:"name"`
Nodes []Node          `json:"nodes,omitempty"`
Left  *Node           `json:"left,omitempty"`
Named map[string]Node `json:"named,omitempty"`
}
```
This pr breaks the cycle in findInType by adding `visited map[reflect.Type]bool` as a parameter.
I haven't spent much time figuring out semantics and usage of findInType, so it might be a wrong solution. However I would like to hear your thoughts on the issue.
=> feat: breaks infinite cycle when looking for fields in recursive structures.

docs/docs/features/request-inputs.md, huma.go, huma_test.go
I'm not entirely sure if this is the direction you want to go in. But this makes adding simple upload endpoints more approachable.
=> Multipart Form RawBody Type Support

docs/docs/features/request-validation.md, huma.go, schema.go, schema_test.go
Attempting to address https://github.com/danielgtaylor/huma/issues/327 which will allow the use of the `hidden` validation tag on Body fields. To avoid double checking of the hidden tag, I moved the existing check from findParams() to only be in SchemaFromField(). All existing tests are passing, however I am not familiar enough with the entire repository to guarantee correctness. Any feedback is welcome.
Fixes #327.
=> feat: hidden body field support

huma.go
This PR fixes a couple minor issues pointed out in #324.
=> fix: allow multipart with body; prevent double status

README.md
This adds our new sponsors into the README and updates the image links to support dark mode better.
=> docs: add sponsors; add dark mode images

docs/mkdocs.yml
Page footer displays a copyright message, this updates it to 2024. I'm a few months late 😊
=> fix: update docs page copyright to 2024

schema.go, schema_test.go
Based on a [comment](https://github.com/danielgtaylor/huma/issues/238#issuecomment-2016448086) by @lazharichir this was an annoying bug where `json:",omitempty"` resulted in blank names in Huma-generated schemas. This is actually allowed by the standard library and means to just re-used the field name, so Huma now follows that same logic.
=> fix: support fields with ,omitempty but no name

adapters/adapters_test.go, adapters/humaecho/humaecho.go, adapters/humafiber/humafiber.go, adapters/humagin/humagin.go, adapters/humago/humago.go, api.go, api_test.go, defaults.go, docs/docs/features/bring-your-own-router.md, humatest/humatest.go, transforms.go
This PR is an alternative approach to #305 by @burgesQ to enable serving the OpenAPI and schemas at the correct path when given a router group / sub-router at some base path like `/api`. It works like this:
```go
mux := chi.NewMux()
mux.Route("/api", func(r chi.Router) {
config := huma.DefaultConfig("My API", "1.0.0")
config.Servers = []*huma.Server{{URL: "https://example.com/api"}}
api = humachi.New(r, config)
// TODO: register operations
huma.Get(api, "/demo", ...)
})
http.ListenAndServe("localhost:8888", mux)
```
This creates a sub-router at `/api` and then sets the `https://example.com/api` server URL including the base path. The sub-router is used to create the Huma instance. The `/demo` route registered via Huma then becomes `/api/huma` when the service is running, and all the …
=> feat: support OpenAPI servers base path & router groups

transforms.go
Suggested by @ant1g in #334, this adds the correct schema path as an example for `$schema` fields. If provided in `OpenAPI().Servers`, the server URL is used as well.
=> feat: add example to $schema links

api.go, docs/docs/features/api-docs.md
Hi there, Thanks for Huma. 
It's been a really nice experience so-far. As I'm using the framework to develop a third-party friendly API I saw a small improvement that could help with the experience. Feel free to close or merge ;) 
The automatic API documentation has the default title of "Elements in HTML". This PR changes that page title to something more identifiable. 
The change assumes that `config.Info` is not `nil`. The GoDoc describes that it is required but I'm too new to the framework to make a educated guess if it's enforced or not.
=> feat: use config.Info.Title as the page title in the API docs

README.md, docs/docs/index.md, docs/mkdocs.yml, docs/overrides/partials/toc.html
Updates the list of sponsors, adds the sponsors to the right part of the project homepage under the TOC links.
=> docs: add sponsors to docs homepage

docs/docs/features/request-inputs.md, schema.go, schema_test.go, validate_test.go
This adds support for `json.RawMessage` which generates an empty schema (no validation). This means any input is valid and it's up to the handler code to determine if there are any errors.
Fixes #348.
=> feat: support json.RawMessage

openapi.go
Just fixes a small typo in the OpenAPI struct ref docs.
Almost seems not worth opening a PR for, but I figured whatever right 🤷‍♂️ Happy hacktoberfest! /s 🎃 😅
=> docs: fixed typo in reference docs

docs/docs/features/middleware.md
Small documentation fix - you cannot set headers after the body has already been written. A more advanced middleware could capture the body in memory before setting a header, but that is beyond the scope of this example.
Fixes #355.
=> docs: fix middleware header example

autopatch/autopatch.go, casing/casing.go, casing/casing_test.go, go.mod, go.sum, huma.go, humacli/humacli.go
This small change vendors the casing library to get rid of another hard dependency. The library hasn't changed in years and is one small file.
=> fix: vendor casing library

.github/workflows/ci.yaml, adapters/humaflow/flow/flow.go, adapters/humaflow/flow/flow_test.go, adapters/humaflow/humaflow.go, api_test.go, huma_test.go, humatest/humatest.go, humatest/humatest_test.go, registry.go, validate_test.go
This PR decouples the `humatest` package from the Chi router, which was a pain for anyone using a router other than Chi. It also forced a non-stdlib dependency when using the `humago` stdlib adapter, which is not ideal. Because we can't yet rely on Go 1.22's stdlib router (Huma works with Go 1.20+), this embeds a tiny little 200 line router package used for testing. You can continue to use `humatest.Wrap` to wrap any other router/API as desired.
This is a slight breaking change due to the removal of Chi in some function signatures, but worth it to fix the larger dependency issue. I am treating it as a fix rather than a major breaking change and will put plenty of notes about it in the release.
Additionally, this makes the dumped request/response during testing more readable (pretty prints …
=> fix: do not require Chi for humatest

adapters/humabunrouter/humabunrouter.go, adapters/humachi/humachi.go, adapters/humaecho/humaecho.go, adapters/humafiber/humafiber.go, adapters/humaflow/humaflow.go, adapters/humagin/humagin.go, adapters/humago/humago.go, adapters/humahttprouter/humahttprouter.go, adapters/humamux/humamux.go, api.go, api_test.go
For middlewares that needs to log the status result of a request, or needs to commit/rollback transactions based on the success of the handler, it'd be handy to be able to query the response status. 
In a [recent comment](https://github.com/danielgtaylor/huma/issues/302#issuecomment-1993236171) you mentioned another solution, 
```go
type MyContext struct {
huma.Context
status int
}
func (c *MyContext) SetStatus(code int) {
c.status = code
c.Context.SetStatus(code)
}
```
Except this doesn't work because `huma.Context` conflicts with the method named `Context()` in the interface definition of `huma.Context`. It gives the error: `cannot use myCtx (variable of type *MyContext) as huma.Context value in argument to next: *MyContext does not implement huma.Context (*MyContext.Context is a field, …
=> Add the ability to get ctx.Status()

huma.go, huma_test.go
This sets the parameter description from the schema description if one is available, enabling descriptions for a wider range of tools, including SwaggerUI.
Fixes #365
=> feat: add param descriptions from schemas

.github/workflows/ci.yaml, huma_test.go, transforms.go
This catches a panic related to an unsupported feature of Go that you might run into with types from third-party libraries. The schema transformer prints a warning, skips the type for inserting links, and moves on. We cannot support this until the underlying language is updated, but at least it won't stop your service from running.
Fixes #371
=> fix: catch reflect.StructOf panics in schema transformer

error_test.go, huma.go, huma_test.go
This updates the code to allow wrapping of the HTTP status errors, which can be useful to provide additional context for logging among other things. Adds a couple of tests to ensure it works as expected.
Fixes #380.
=> fix: use errors.As to get StatusError, enabling wrapping

api.go, docs/docs/features/middleware.md, huma.go, huma_test.go, openapi.go
This PR introduces a small change to add per-operation router-agnostic middleware using the existing `huma.Operation` struct configured at operation registration time. It can be used like this, which also facilitates wrapping/composition utility functions:
```go
huma.Register(api, huma.Operation{
Method: http.MethodGet,
Path:   "/demo",
Middlewares: huma.Middlewares{
func(ctx huma.Context, next func(huma.Context)) {
// TODO: implement middleware here...
next(ctx)
},
},
}, func(ctx context.Context, input *struct{}) (*struct{}, error) {
// TODO: implement handler here...
return nil, nil
})
```
Let me know what you think. Fixes #378.
=> feat: add per-operation router-agnostic middleware

error_test.go, huma_test.go, humatest/humatest.go, humatest/humatest_test.go
I noticed if you supply an empty config struct you get an unhelpful panic with `invalid memory address or nil pointer dereference`. This PR changes the panic to supply a helpful message describing the problem. 
An alternative solution would be to make it so that an empty huma.Config{} doesn't panic at all.
=> must specify openapi config

README.md, defaults.go, docs/docs/features/index.md, docs/docs/features/response-serialization.md, docs/docs/how-to/graceful-shutdown.md, docs/docs/how-to/image-response.md, docs/docs/terminal/install.cast, docs/docs/tutorial/client-sdks.md, docs/docs/tutorial/installation.md, docs/docs/tutorial/sending-data.md, docs/docs/tutorial/service-configuration.md, docs/docs/tutorial/writing-tests.md, docs/docs/tutorial/your-first-api.md, examples/cookies/main.go, examples/custom-error/main.go, examples/greet/main.go, examples/omit/main.go, examples/oneof-response/main.go, examples/param-reuse/main.go, examples/resolver/main.go, examples/spec-cmd/main.go, examples/sse/main.go, examples/v1-middleware/main.go, formats/cbor/cbor.go, formats/cbor/cbor_test.go
This PR makes the CBOR format optional in Huma's default config, removing the hard dependency and providing more flexibility in how default formats are set up. Technically this is not a breaking change, just a change in how defaults work, however existing users who wish to continue using CBOR must add a new import. If you set up your own config you are unaffected.
- Moves CBOR support into `github.com/danielgtaylor/huma/v2/formats/cbor`
- Creates a `huma.DefaultFormats` map which packages can modify. This is used by `huma.DefaultConfig(...)`.
- Uses the `init()` function to modify the default formats map when the `cbor` package is imported. This is similar to how the standard library works and described in [Effective Go](https://go.dev/doc/effective_go#blank_import), e.g. see …
=> fix: make cbor support optional

huma.go
This fixes a bug for some routers & Go versions where attempting to write a body after a status code of 204 No Content or 304 Not Modified have been sent results in a panic.
=> fix: do no try to write 204/304 body if present

docs/docs/features/request-inputs.md, schema.go, schema_test.go
Hey! I realised after opening my issue on this (#395), that this should be a pretty trivial issue to resolve. 
Please let me know if I've missed anything with this PR, and thanks again for all that you do!
=> Support `netip.Addr` as a special type

docs/docs/features/response-errors.md, error.go, error_test.go, huma.go
This feature uses the new error wrapping capabilities to let you wrap any existing error with additional headers.
Fixes #386.
=> feat: wrap errors to set headers

schema.go, schema_test.go
Problem:
Currently the Schema(r Registry) *Schema on types that implement a custom schema will only be called if the field is not a pointer. 
Solution:
In the function SchemaFromType we first deref the type so that we always compare a non pointer type against the interface. 
fixes: #412
=> fix: check if struct implements interface SchemaProvider after deref

adapters/humaflow/flow/flow.go, adapters/humaflow/flow/flow_test.go
**Problem**:
The current implementation does not allow to use of encoded named parameters like:
`/path/:param` - `/path-params/a%3A%2F%2Fb%2Fc`
Which is fully legal by [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt)
Solution:
Use [EscapedPath()](https://pkg.go.dev/net/url#URL.EscapedPath) instead of direct access to a `u.Path`
> Note that the Path field is stored in decoded form: /%47%6f%2f becomes /Go/. A consequence is that it is impossible to tell which slashes in the Path were slashes in the raw URL and which were %2f. This distinction is rarely important, but when it is, the code should use the [URL.EscapedPath](https://pkg.go.dev/net/url#URL.EscapedPath) method, which preserves the original encoding of Path.
Details:
https://pkg.go.dev/net/url#URL
PR into the original package: …
=> fix: Add support for Percent-Encoding RFC 3986

huma_test.go, transforms.go
This uses reflection to check for nil which is more robust and can prevent a panic/500 error from happening if the operation returns successful with a nil body.
=> fix: more robust nil check for link transformer

schema.go, schema_test.go
Add basic support for the OpenAPI 3.1 discriminator object in schemas. https://spec.openapis.org/oas/v3.1.0#discriminator-object
Fixes #384
=> feat: basic schema discriminator support

conditional/params.go
This updates the error locations for precondition failed response errors to match the format used by Huma, where the `request.` portion is not explicit. This improved consistency within the project.
=> fix: precondition error location to match other errors

huma.go, huma_test.go
Small change introducing the possibility to provide name hints for request/response body through struct tags. Previously discussed in #322
Example: 
```go
type EndpointInput struct {
Body struct {
SomeData string `json:"some_data"`
} `name-hint:"SomeName"`
}
```
Because it defines a name hint, it only applies to anonymous types. We could go further and allow overriding the name altogether but that would involve changing the schema namer interface (`func (t reflect.Type, hint string) string`) to include one more parameter, which might break backward compatibility.
=> Allow providing name hints using tags for anonymous body structs

schema.go
This PR adds the `contentMediaType` property to the generated schema spec for binary field. This is mainly for the purpose of compatibility with API documentation tools such as Stoplight Elements (see #397).
Note that #415 sets `contentType` property in the schema, but that is not sufficient for Stoplight to show the file upload UI component, event though the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#considerations-for-file-uploads) says `contentMediaType` is not required when `contentType` is defined. 
Although that may rather be an issue in Stoplight, in my understanding it does not hurt to add this redundancy to Huma.
Thus, this PR can be considered independently from #415. I hope I'm not mistaken about what the OpenAPI specs say, let me know if you think this rather belongs …
=> Add contentMediaType field to generated schema when format is binary

adapters/adapters_test.go, adapters/humachi/humachi.go, go.mod, go.sum
V4 has been deprecated for 7 months since [da7ce946](https://github.com/go-chi/chi/commit/da7ce9468546b9c352b0c7eac3580961543d0d96)
We could also split it into a different package, but IMHO the maintenance overhead doesn't seem worth it for a deprecated version. People can still maintain separate adapter, since there are no huma-internal dependencies. 
Fixes #423
=> feat!: drop chi v4 adapter

huma.go, huma_test.go
Ran into this problem where a dev tried to use *int for a response, and the panic wasn't clear about what to fix. This tries to point the dev in the right direction.
=> panic with more descriptive messages

humacli/humacli_test.go
This PR fixes a minor race condition detected with `go test -race`, and the updated code serves as a better example for anyone looking over the test suite.
=> fix: race condition in CLI tests

README.md
Fixes Zuplo formatting which was overflowing.
=> docs: fix formatting in sponsors

huma.go
This fixes an order-of-operations bug that was due to copy/paste and removal of `defer` statements, however defers execute in reverse order while the copied statements execute in order. This means the buffer could be sent back into the pool before getting reset, causing a potential race on the next read. This was a silly mistake that should have been caught with the race detector during tests but was unfortunately missed. Sorry about that!
Fixes #552
=> fix: order of operations when resetting buffer

middleware/recovery.go
This small bug fix adds a buffer reset that was missing and would sometimes result in multiple request bodies being dumped into the same buffer when under heavy load.
Unfortunately this is difficult to unit test.
=> fix: reset recovery middleware buffer

formdata.go, huma.go, schema.go, schema_test.go
This PR prevents overwriting of schema validation fields when using a `SchemaTransformer` or other mechanism where parsing a struct field with tags could result in overwritten field values such as `pattern`. The various tag functions have been updated to take the current field value as the default rather than returning the zero value as default.
Fixes #557
=> fix: prevent overwriting schema validations

openapi.go
This fixes a mistake with how the `Operation.Callbacks` get defined. It should be a map of name to map of URL expression to path item object, as described in the linked issue. This is only used by external tools, so no tests within Huma for now.
Fixes #653.
=> fix: operation callbacks shape

huma.go, huma_test.go
This updates the handling of the raw body field index to match that of the body index (using a slice of field integers describing the path to the possibly embedded field). This makes it possible to use embedded structs with a `RawBody` field.
Fixes #652
=> feat: support embedded raw body fields

huma.go, huma_test.go
This PR takes into account when a response body has a `ContentTypeFilter` implemented and uses `application/json` as its input to determine the output content type to be used in the generated OpenAPI document.
Fixes #559.
=> fix: body with ContentTypeFilter should update OpenAPI

docs/docs/how-to/oauth2-jwt.md
mermaid has some problem where `1.` is interpreted as markdown and doesn't render properly. Not sure if that's a recent problem, but it manifests like so:
changing to `1:` avoids this problem.
=> fix oauth2-jwt.md mermaid rendering issue

.golangci.yml, huma.go, humacli/humacli_test.go
The PR enables [`unconvert`](https://golangci-lint.run/usage/linters/#unconvert) and [`tenv`](https://golangci-lint.run/usage/linters/#tenv) linters in golangci-lint config and fixes appeared lint issues.
=> chore: enable unconvert and tenv linters

huma.go
If `err` is `nil`, `form` can't be `nil`.
If `err` is `nil` and `form` is `nil`, there will be a panic on the line:
```go
Message:  "cannot read multipart form: " + err.Error(),
```
=> refactor: simplify error handling for multipart form reading

huma_test.go
The PR fixes the assertion for `TestFeatures/response-image`.
`assert.NotEmpty(t, "binary", api.OpenAPI().Paths["/response-image"].Get.Responses["200"].Content["image/png"])` checks that `"binary"` is not empty, which is useless.
=> fix: useless assertion in TestFeatures/response-image

huma.go
This attempts to fix a hard-to-repro race condition when returning an error due to marshaling that includes a reference to the body bytes that will get returned to the pool for re-use before the output is done. The fix here is to cast the bytes to a string, which creates a copy that is safe to reference later.
Fixes #685.
=> fix: potential body error race

huma.go, huma_test.go
In v2.22.1, I used the display of examples in the swagger.
In v2.23.0 this was broken by adding the line 
```
op.RequestBody.Content[contentType] = &MediaType{Schema: s}
```
https://github.com/danielgtaylor/huma/compare/v2.22.1...v2.23.0#diff-34398007f1f21b0bc55b2fe31480add48b936399f37e1ae49662d9e4dbf33a98R598
Now with the upgrade to v2.23.0+ all my examples are being overwritten and not displayed in swagger.
Made a small fix to make it work for me as before.
Or is there another more correct way to display examples?
=> Fix examples

formdata.go, huma.go, huma_test.go
The current [`huma.Register`](https://github.com/danielgtaylor/huma/blob/v2.27.0/huma.go#L607) function is 900+ lines of code and has [up to 9 levels of nesting](https://github.com/danielgtaylor/huma/blob/v2.27.0/huma.go#L1378). While working on #694 I found it really hard to understand the logic. In my effort to understand the function, I performed several refactorings and I thought that you may appreciate them as well.
Surely some parts are a matter of taste -- I don't mind changing them.
Looking forward to your thoughts.
=> refactor: split up huma.Register

docs/docs/features/request-inputs.md, formdata.go, huma.go, huma_test.go
@danielgtaylor I started working on #694. The first part of the work is a major refactoring that I submitted separately in #705. The second part is a feature where MultipartFormFiles also parses and validates multipart.Form.Value into the input struct. The diff is probably clearer in [this PR](https://github.com/b-kamphorst/huma/pull/1).
At time of writing, the added feature only parses fields that have a `form` tag, mostly because I copied the approach for parsing and validating other request parameters and I was not quite sure how to do that differently. Before I continue, I would much like to hear your thoughts:
1. Would you consider this feature for Huma?
2. If so, do you have any feedback on how to continue with this PR?
Closes #694.
=> feat: allow arbitrary fields in MultipartFormFiles

huma.go, huma_test.go
This PR fixes a regression introduced in #705, described in #717.
While hardening test cases, I noticed that slices of uint8s were not supported, so I took the liberty to also add the implementation (in a separate commit though, which can be reverted if this was intentional).
Fixes #717
=> fix: double validation errors

huma.go, huma_test.go
This PR makes it possible to provide a custom request schema along with a body by preventing Huma from overwriting any existing schema for the default content type.
=> fix: allow providing a custom request schema

huma_test.go, transforms.go
This PR ensures the schema link transformer only runs when the ref is a valid intra-document (local) ref and not an external one. External ones are ignored.
Fixes #703.
=> fix: do not panic when encountering external schemas

.github/workflows/ci.yaml, adapters/humafiber/humafiber.go, adapters/humafiber/humafiber_context_test.go
Fiber and FastHttp has the very strict rules how to work with Context() and UserContext()
If some huma-based application, whatever reason, has references to context.Context outside of Huma handler, then fiber/fasthttp RequestCtx does not work as expected, the most likely you receive crash or race-condition
To prevent race conditions and possible issues with graceful shutdown of the servers, this pull request completely fix the way on how fiber and huma integrated.
It also include golang tests to detect race conditions.
=> fixed work with fiber.Ctx, fiber.UserContext - fixed graceful shutdown and race condition on access to huma.Context outside handler

docs/docs/features/groups.md, docs/docs/features/middleware.md, docs/mkdocs.yml, group.go, group_test.go, huma.go
This PR adds a new `Group` struct & feature that takes the functionality of the excellent https://github.com/cardinalby/hureg library and ports it into Huma's core. Basic functionality looks like this:
```go
grp := huma.NewGroup(api, "/v1")
grp.UseMiddleware(authMiddleware)
huma.Get(grp, "/users", func(ctx context.Context, input *struct{}) ([]User, error) {
// ...
})
```
Check out the included docs for more info!
Related to #719.
Fixes #489.
=> feat: groups

docs/docs/features/request-validation.md, schema.go, schema_test.go
Add support for using the new `omitzero` field tag introduced in go-1.24 to mark those fields as optional/not-required
https://tip.golang.org/doc/go1.24#encodingjsonpkgencodingjson
> When marshaling, a struct field with the new omitzero option in the struct field tag will be omitted if its value is zero.
- Added a new check for `omitzero` to mark field as optional in `schema.go`
- Added new tests in to check `omitempty` and `omitzero` in `schema_test.go`
- Mentioned the new tag in `request-validation.md` docs
Lmk if there are other files/places that need changing for this change.
=> Add 'omitzero' support to mark optional fields

docs/docs/features/groups.md
The PR corrects `UseSimpleModifier` example code.
=> docs: fix typo in groups

huma.go, huma_test.go
Hi,
Thank you again for your work on this project!
I just noticed that the `head` method is missing here. Hopefully, this small addition will be helpful to others. :)
=> feat: adding the head method to the list of convenience wrappers

defaults.go, huma_test.go
Be default, JSON output is escaped to better support embedding it into HTML. This is extremely unlikely to be needed for HTTP APIs as they have different access patterns. This changes the default behavior to not escape, while letting people who do need the feature set it up in their `huma.Config.Formats` map as needed.
For example, `expected number \u003e= 10` becomes `expected number >= 10` after this change.
=> fix: do not HTML escape JSON output by default

validate.go, validate_test.go, validation/messages.go
This adds an additional check for integers using `math.Trunc(...)` to try and fail earlier with a more reasonable error message for users passing in floating point values for integers.
Fixes #745. (not entirely, but it's an improvement)
=> fix: better integer validation checks

huma.go, schema.go
This simple patch allows to explicitly set the "example" tag of fields in both params an schemas to the empty string "" .
=> fix: Allow explicitely setting the "example" tag to the empty string

openapi.go
Just a minor doc improvement referencing the canonical source for auth schemes.
=> chore(docs): add link to IANA auth schemes

api.go
This small PR just extends the usage of ErrUnknownContentType to a couple more places where the error was not being wrapped and the error string was being duplicated.
AFAICT that shouldn't have any negative side-effects, except for making error testing a bit more consistent?
=> minor: use ErrUnknownContentType in more places

huma.go
When an empty file field is submitted in a form (`multipart/form-data`), `form.Value` contains an empty string (`""`), but `form.File` is missing. This leads to a panic with the error:  `unsupported param type huma.FormFile`
Now, before accessing `form.Value[p.Name]`, we check if the value is an empty string and handle it correctly. If the parameter is required and not a valid file, a proper validation error is returned instead of causing a panic.
=> Fix panic when sending an empty file field in a form

validate.go, validate_test.go
Same as `With()`, but takes and int, calls `PushIndex`, converts to a string, then pops.
Found myself wishing for this functionality today, but not a deal breaker if it doesn't make it in. Just a little more convenient.
I did not see any tests for pathbuffer itself, but since this method wouldn't be covered elsewhere I added a test for it.
=> Add WithIndex to PathBuffer

sse/sse.go, sse/sse_test.go
=> fix: make order of SSE events stable in openapi

group_test.go, huma.go
Hello! I recently found out the validation of the `path` parameter prevented the use of an empty string in the path.
In my use case I found myself in this situation:
- I wanted to create a `/resource` API Group, with CRUD for `resource`, plus some sets of endpoints for sub-resources (ie: `/resource/:id/stuff`)
- I got a `StripSlashes` middleware (required to handle legacy clients), which trims any `/` from incoming requests
- Since I have `StripSlashes`, If I want to add a  `POST /resource/` I need to actually define the route as `POST /resource`
- The above is not possible because of the strict validation done in `Register`
https://github.com/danielgtaylor/huma/blob/6bfeebae55ed05e1e909041c5e3692dc168cd066/huma.go#L625-L626
With this PR I relaxed the validation of the `Path` parameter, …
=> Allow empty path in group operations

adapters/humamux/humagmux_test.go, adapters/humamux/humamux.go, adapters/humamux/options.go
This MR adds an option to the Gorilla mux adapter, allowing customizing the mux route.
This allows, for example, adding standard HTTP handlers per route, maybe using `huma.Operation.Metadata` as input parameters.
=> Add option to customize the Gorilla Mux route

adapters/adapters_test.go, adapters/humabunrouter/humabunrouter.go, adapters/humachi/humachi.go, adapters/humaecho/humaecho.go, adapters/humafiber/humafiber.go, adapters/humaflow/humaflow.go, adapters/humagin/humagin.go, adapters/humago/humago.go, adapters/humahttprouter/humahttprouter.go, adapters/humamux/humamux.go, api.go
Closes https://github.com/danielgtaylor/huma/issues/790
Closes https://github.com/danielgtaylor/huma/issues/784
Since I was also affected by this issue I decided to open a PR
I used the (very naive) strategy of exposing a func to extract the original `huma.Context` from a `subContext`, and made use of it in every `adapter.Unwrap(ctx)` func.
I updated the adapters test to make sure all adapters don't panic while adding a simple context value (and added the missing `humago` test case)
While updating the test I also discovered that  `humabunrouter.Unwrap(ctx)` simply doesn't work with Bun in compat mode. I didn't fix it since it's not really related to this change, and I wasn't sure on the preferred way (duplicated func? new package? return *http.Request for both context implementations?)
=> Fix adapter.Unwrap() not working after huma.WithContext() 

humacli/humacli.go, humacli/humacli_test.go
This PR adds support for nested options in CLI configurations, particularly
when using pointer-to-struct fields. It addresses an issue where the CLI would
panic with `panic: Unsupported option type: ptr` or `panic: Unsupported option type: struct`
when attempting to set values on fields within a nil pointer struct.
I was trying to implement nested configuration options with pointers for a clean optional field pattern:
```go
type DatabaseConfig struct {
Host     string `doc:"Database host"`
Port     int    `doc:"Database port" default:"5432"`
Username string `doc:"Database username"`
}
type AppConfig struct {
Debug bool            `doc:"Enable debug mode"`
DB    *DatabaseConfig `doc:"Database configuration"` // Here both ptr or direct would have been acceptable.
}
```
When attempting to …
=> Fix: Support for nested pointer struct fields in CLI options

schema.go, schema_test.go
TestUnexportedEmbed demonstrates how the JSON is serialized. This fixes the generated spec so those fields are documented.
Fixes #444
=> fix: export of embed properties when struct type is not exported

.github/workflows/ci.yaml
Potential fix for [https://github.com/danielgtaylor/huma/security/code-scanning/5](https://github.com/danielgtaylor/huma/security/code-scanning/5)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the least privileges required for the workflow to function correctly. Based on the actions used in the workflow, the following permissions are appropriate:
- `contents: read` for accessing repository files.
- `pull-requests: write` if the workflow interacts with pull requests (though this is not evident in the current workflow).
The `permissions` block can be added at the root level of the workflow to apply to all jobs or within the `build` job to limit permissions specifically for that job.
_Suggested fixes powered by Copilot Autofix. Review …
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

schema.go, schema_test.go
Reverts danielgtaylor/huma#822. With some additional testing this appears to not be working correctly. The stdlib JSON serializer is ignoring these private embedded fields. We should revisit this and see if there is a solution that can work.
=> Revert "fix: export of embed properties when struct type is not exported"

api.go, huma.go, huma_test.go
PR for #843 
- Added `NoFormatFallback` field to `Config` to control format fallback.
- Added positive and negative test for unknown/invalid Accept header (had to modify test harness for `Config`).
- Fixed a bug(?) with how Content-Type was _not_ set for 406 responses by moving setting of the Content-Type into the `transformWrite()`.
=> feat: #843 Allow 406 Not Acceptable with NoFormatFallback config

huma.go, huma_test.go
This PR reverts part of #850 and adjusts the code so the tests for it still pass while maintaining the correct overall behavior for setting the content type.
Fixes #851
=> fix: content type bug introduced in #850
